[project]
name = "lmbench"
version = "0.2.0"
description = "A benchmarking tool for evaluating Large Language Models for use in the public sector."
authors = [{ name = "BDR" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "python-dotenv>=1.0.0",
    "pandas>=2.0.3",
    "rich>=13.9.3",
    "rouge-score>=0.1.2",
    "bert-score>=0.3.13",
    "evaluate==0.4.6",
    "openai>=2.9.0",
    "ollama>=0.5.3",
    "anthropic>=0.40.0",
    "pydantic>=2.9.2",
    "omegaconf>=2.3.0",
    "fastparquet>=2024.5.0",
    "tqdm>=4.66.5",
    "mlflow-skinny>=2.17.0",
    "tiktoken>=0.12.0",
    "lxml>=5.3.0",
    "openpyxl>=3.1.5",
    "transformers>=4.46.2,<5",
    "ragas==0.4.3",
    "tenacity<9.1.5",
    "sentencepiece>=0.2.0",
    "scikit-learn>=1.6.1",
    "ecologits==0.8.2",
    "langchain-core>=0.3.74",
    "langchain-openai>=0.3.12",
    "langchain-community<0.4.2",
    "fasttext>=0.9.3",
    "diskcache>=5.6.3",
    "sqlitedict>=2.1.0",
    "stanza>=1.11.0",
    "codecarbon>=3.0.8",
    "dspy>=3.1.3",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-asyncio>=1.1.0",
    "pytest-httpserver>=1.1.0",
    "pytest-mock>=3.14.0",
    "pytest-watch>=4.2.0",
    "pytest-testmon>=2.1.1",
    "ruff>=0.7.0",
    "seaborn>=0.13.2",
    "notebook>=7.3.2",
    "pandas-stubs>=2.3.0.250703",
    "basedpyright>=1.36.1",
    "scipy-stubs~=1.18.0",
    "pytest-rerunfailures>=16.2",
]

[project.scripts]
lmbench = "lmbench.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = [
    "F", # Pyflakes
    "E", # Pycodestyle
    "UP",
    "W",
    "I", # isort
    "D", # pydocstyle
    "ARG", # flake8-unused-arguments
]
ignore = [
    "D205",
    "D203", # one-blank-line-before-class
    "D212", # multi-line-summary-first-line
    "D404", # docstring-starts-with-this
]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D"]
"notebooks/*" = ["D", "ARG", "E501", "E741", "I001", "W293", "F401", "F821", "F541"]

[tool.basedpyright]
typeCheckingMode = "standard"
exclude = ["notebooks", "tests"]
