"""This module contains the abstract definition of a Tokenizer."""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from lmbench.models.abstract import LLM
    from lmbench.models.data_models import LLMMessage


class Tokenizer:
    """Abstract implementation of a tokenizer that is used to adapt message lengths to the llms."""

    llm: "LLM"
    name: str

    def __init__(self, llm: "LLM"):
        """Initialize the tokenizer with an instance of a language model.

        Args:
            llm (LLM): The model that uses this tokenizer.
        """
        self.llm = llm

    def num_tokens(self, messages: list["LLMMessage"]) -> int:
        """Return the number of tokens generated by the messages.

        Args:
            messages (list[LLMMessage]): The list of messages to get the token size of.

        Returns:
            int: Number of tokens generated by the tokenizer
        """
        raise NotImplementedError
